name: .NET Publish and Release

on:
  push:
    branches:
      - main

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore EmbedCodeInMarkdown/EmbedCodeInMarkdown.csproj

        # check that scripts compile without error
      - name: Build
        run: dotnet build --no-restore EmbedCodeInMarkdown/EmbedCodeInMarkdown.csproj

      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

